version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 16
    commands:
      - set -e
      - apt-get update -y
      - apt-get install -y libpq-dev libzip-dev
      - apt-get install -y php-mysql
      # php-pgsql
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - cp ".env.${ENVIRONMENT_TYPE}" .env
      - composer install
      - npm install
      # - npm install --global cross-env
      # - chmod +x .platform/hooks/prebuild/*.sh
      - chmod +x .platform/hooks/postdeploy/*.sh
  build:
    commands:
      - npm run $ENVIRONMENT_TYPE
      - php artisan migrate --force
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes